name: Trigger auto deployment for bgfood-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/bgfood-app-AutoDeployTrigger-ae12955a-b027-4bc5-a717-0eba6c9cdc42.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BGFOODAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BGFOODAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BGFOODAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.BGFOODAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BGFOODAPP_REGISTRY_PASSWORD }}
          containerAppName: bgfood-app
          resourceGroup: bgfood
          imageToBuild: labg94/bgfood-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


